version: '3.8'

services:
  momenture-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
      - ./logs/laravel:/var/www/html/storage/logs
    env_file:
      - .env
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - momenture-db


  momenture-db:
    image: postgres:15
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
